# Generated by Django 5.2.4 on 2025-08-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_apikey_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_api_key_name_per_user'),
        ),
    ]
